all: one two four eight

one: project3.c
	gcc -DNUMT=1 -DNUMPAD=0 -o proj3-onet-f1-n0 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=1 -o proj3-onet-f1-n1 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=2 -o proj3-onet-f1-n2 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=3 -o proj3-onet-f1-n3 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=4 -o proj3-onet-f1-n4 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=5 -o proj3-onet-f1-n5 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=6 -o proj3-onet-f1-n6 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=7 -o proj3-onet-f1-n7 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=8 -o proj3-onet-f1-n8 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=9 -o proj3-onet-f1-n9 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=10 -o proj3-onet-f1-n10 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=11 -o proj3-onet-f1-n11 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=12 -o proj3-onet-f1-n12 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=13 -o proj3-onet-f1-n13 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=14 -o proj3-onet-f1-n14 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=15 -o proj3-onet-f1-n15 -fopenmp project3.c -std=c99


two: project3.c
	gcc -DNUMT=2 -DNUMPAD=0 -o proj3-twot-f1-n0 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=1 -o proj3-twot-f1-n1 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=2 -o proj3-twot-f1-n2 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=3 -o proj3-twot-f1-n3 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=4 -o proj3-twot-f1-n4 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=5 -o proj3-twot-f1-n5 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=6 -o proj3-twot-f1-n6 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=7 -o proj3-twot-f1-n7 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=8 -o proj3-twot-f1-n8 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=9 -o proj3-twot-f1-n9 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=10 -o proj3-twot-f1-n10 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=11 -o proj3-twot-f1-n11 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=12 -o proj3-twot-f1-n12 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=13 -o proj3-twot-f1-n13 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=14 -o proj3-twot-f1-n14 -fopenmp project3.c -std=c99
	gcc -DNUMT=2 -DNUMPAD=15 -o proj3-twot-f1-n15 -fopenmp project3.c -std=c99

four: project3.c
	gcc -DNUMT=1 -DNUMPAD=0 -o proj3-fourt-f1-n0 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=1 -o proj3-fourt-f1-n1 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=2 -o proj3-fourt-f1-n2 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=3 -o proj3-fourt-f1-n3 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=4 -o proj3-fourt-f1-n4 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=5 -o proj3-fourt-f1-n5 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=6 -o proj3-fourt-f1-n6 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=7 -o proj3-fourt-f1-n7 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=8 -o proj3-fourt-f1-n8 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=9 -o proj3-fourt-f1-n9 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=10 -o proj3-fourt-f1-n10 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=11 -o proj3-fourt-f1-n11 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=12 -o proj3-fourt-f1-n12 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=13 -o proj3-fourt-f1-n13 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=14 -o proj3-fourt-f1-n14 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=15 -o proj3-fourt-f1-n15 -fopenmp project3.c -std=c99

eight: project3.c
	gcc -DNUMT=1 -DNUMPAD=0 -o proj3-eightt-f1-n0 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=1 -o proj3-eightt-f1-n1 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=2 -o proj3-eightt-f1-n2 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=3 -o proj3-eightt-f1-n3 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=4 -o proj3-eightt-f1-n4 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=5 -o proj3-eightt-f1-n5 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=6 -o proj3-eightt-f1-n6 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=7 -o proj3-eightt-f1-n7 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=8 -o proj3-eightt-f1-n8 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=9 -o proj3-eightt-f1-n9 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=10 -o proj3-eightt-f1-n10 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=11 -o proj3-eightt-f1-n11 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=12 -o proj3-eightt-f1-n12 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=13 -o proj3-eightt-f1-n13 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=14 -o proj3-eightt-f1-n14 -fopenmp project3.c -std=c99
	gcc -DNUMT=1 -DNUMPAD=15 -o proj3-eightt-f1-n15 -fopenmp project3.c -std=c99

one-tests: one
	./proj3-onet-f1-n0 
	./proj3-onet-f1-n1 
	./proj3-onet-f1-n2 
	./proj3-onet-f1-n3 
	./proj3-onet-f1-n4 
	./proj3-onet-f1-n5 
	./proj3-onet-f1-n6 
	./proj3-onet-f1-n7 
	./proj3-onet-f1-n8 
	./proj3-onet-f1-n9 
	./proj3-onet-f1-n10 
	./proj3-onet-f1-n11 
	./proj3-onet-f1-n12 
	./proj3-onet-f1-n13 
	./proj3-onet-f1-n14
	./proj3-onet-f1-n15

two-tests: two
	./proj3-twot-f1-n0 
	./proj3-twot-f1-n1 
	./proj3-twot-f1-n2 
	./proj3-twot-f1-n3 
	./proj3-twot-f1-n4 
	./proj3-twot-f1-n5 
	./proj3-twot-f1-n6 
	./proj3-twot-f1-n7 
	./proj3-twot-f1-n8 
	./proj3-twot-f1-n9 
	./proj3-twot-f1-n10 
	./proj3-twot-f1-n11 
	./proj3-twot-f1-n12 
	./proj3-twot-f1-n13 
	./proj3-twot-f1-n14
	./proj3-twot-f1-n15

four-tests: four
	./proj3-fourt-f1-n0 
	./proj3-fourt-f1-n1 
	./proj3-fourt-f1-n2 
	./proj3-fourt-f1-n3 
	./proj3-fourt-f1-n4 
	./proj3-fourt-f1-n5 
	./proj3-fourt-f1-n6 
	./proj3-fourt-f1-n7 
	./proj3-fourt-f1-n8 
	./proj3-fourt-f1-n9 
	./proj3-fourt-f1-n10 
	./proj3-fourt-f1-n11 
	./proj3-fourt-f1-n12 
	./proj3-fourt-f1-n13 
	./proj3-fourt-f1-n14
	./proj3-fourt-f1-n15


eight-tests: eight
	./proj3-eightt-f1-n0 
	./proj3-eightt-f1-n1 
	./proj3-eightt-f1-n2 
	./proj3-eightt-f1-n3 
	./proj3-eightt-f1-n4 
	./proj3-eightt-f1-n5 
	./proj3-eightt-f1-n6 
	./proj3-eightt-f1-n7 
	./proj3-eightt-f1-n8 
	./proj3-eightt-f1-n9 
	./proj3-eightt-f1-n10 
	./proj3-eightt-f1-n11 
	./proj3-eightt-f1-n12 
	./proj3-eightt-f1-n13 
	./proj3-eightt-f1-n14
	./proj3-eightt-f1-n15


tests: one-tests two-tests four-tests eight-tests


clean:
	rm -rf proj3-*
