default: all
q0 : q0.c
	gcc -g -Wall -std=c99 -o q0 q0.c
q1 : q1.c
	gcc -g -Wall -std=c99 -o q1 q1.c
q2 : q2.c
	gcc -g -Wall -std=c99 -o q2 q2.c
q3 : q3.c
	gcc -g -Wall -std=c99 -o q3 q3.c
q4 : q4.c
	gcc -g -Wall -std=c99 -o q4 q4.c
q5 : q5.c
	gcc -g -Wall -std=c99 -o q5 q5.c
all:
	gcc -g -Wall -std=c99 -o q0 q0.c
	gcc -g -Wall -std=c99 -o q1 q1.c
	gcc -g -Wall -std=c99 -o q2 q2.c
	gcc -g -Wall -std=c99 -o q3 q3.c
	gcc -g -Wall -std=c99 -o q4 q4.c
	gcc -g -Wall -std=c99 -o q5 q5.c

clean:
	rm q0
	rm q1
	rm q2
	rm q3
	rm q4
	rm q5
