all: compile tests

compile: arraymult-1K arraymult-1M arraymult-2M arraymult-3M arraymult-4M arraymult-5M arraymult-6M arraymult-7M arraymult-8M arraymult-9M arraymult-10M arraymult-11M arraymult-12M arraymult-13M arraymult-14M arraymult-15M arraymult-16M arraymult-17M arraymult-18M arraymult-19M arraymult-20M arraymult-21M arraymult-22M arraymult-23M arraymult-24M arraymult-25M arraymult-26M arraymult-27M arraymult-28M arraymult-29M arraymult-30M arraymult-31M arraymult-32M


simd.p5.o:	simd.p5.h  simd.p5.cpp
		g++ -c  simd.p5.cpp -o simd.p5.o

arraymult-1K:	arraymult.cpp simd.p5.o
		g++ -DNUMM=1000 -o arraymult-1K  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-1M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=1000000 -o arraymult-1M arraymult.cpp simd.p5.o  -lm  -fopenmp 
arraymult-2M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=2000000 -o arraymult-2M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-3M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=3000000 -o arraymult-3M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-4M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=4000000 -o arraymult-4M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-5M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=5000000 -o arraymult-5M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-6M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=6000000 -o arraymult-6M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-7M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=7000000 -o arraymult-7M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-8M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=8000000 -o arraymult-8M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-9M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=9000000 -o arraymult-9M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-10M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=10000000 -o arraymult-10M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-11M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=11000000 -o arraymult-11M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-12M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=12000000 -o arraymult-12M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-13M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=13000000 -o arraymult-13M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-14M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=14000000 -o arraymult-14M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-15M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=15000000 -o arraymult-15M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-16M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=16000000 -o arraymult-16M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-17M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=17000000 -o arraymult-17M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-18M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=18000000 -o arraymult-18M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-19M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=19000000 -o arraymult-19M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-20M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=20000000 -o arraymult-20M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-21M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=21000000 -o arraymult-21M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-22M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=22000000 -o arraymult-22M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-23M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=23000000 -o arraymult-23M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-24M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=24000000 -o arraymult-24M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-25M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=25000000 -o arraymult-25M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-26M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=26000000 -o arraymult-26M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-27M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=27000000 -o arraymult-27M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-28M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=28000000 -o arraymult-28M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-29M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=29000000 -o arraymult-29M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-30M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=30000000 -o arraymult-30M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-31M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=31000000 -o arraymult-31M  arraymult.cpp simd.p5.o  -lm  -fopenmp
arraymult-32M:	arraymult.cpp simd.p5.o
		g++ -DNUMM=32000000 -o arraymult-32M  arraymult.cpp simd.p5.o  -lm  -fopenmp

tests:
	./arraymult-1K
	./arraymult-1M
	./arraymult-2M
	./arraymult-3M
	./arraymult-4M
	./arraymult-5M
	./arraymult-6M
	./arraymult-7M
	./arraymult-8M
	./arraymult-9M
	./arraymult-10M
	./arraymult-11M
	./arraymult-12M
	./arraymult-13M
	./arraymult-14M
	./arraymult-15M
	./arraymult-16M
	./arraymult-17M
	./arraymult-18M
	./arraymult-19M
	./arraymult-20M
	./arraymult-21M
	./arraymult-22M
	./arraymult-23M
	./arraymult-24M
	./arraymult-25M
	./arraymult-26M
	./arraymult-27M
	./arraymult-28M
	./arraymult-29M
	./arraymult-30M
	./arraymult-31M
	./arraymult-32M

clean:
	rm -f arraymult-* *.o
